# Generated by Django 5.2.8 on 2025-12-26 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="지역 필터"
                    ),
                ),
                (
                    "min_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="최소 희망 입찰가"
                    ),
                ),
                (
                    "max_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="최대 희망 입찰가"
                    ),
                ),
                (
                    "min_failures",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="최소 유찰 횟수"
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(default=True, verbose_name="이메일 알림 여부"),
                ),
                (
                    "notify_telegram",
                    models.BooleanField(
                        default=False, verbose_name="텔레그램 알림 여부"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="immediate", max_length=20, verbose_name="알림 빈도"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="알림 사용 여부"),
                ),
                (
                    "large_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_preferences",
                        to="auctions.categorylarge",
                        verbose_name="대분류",
                    ),
                ),
                (
                    "mid_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_preferences",
                        to="auctions.categorymiddle",
                        verbose_name="중분류",
                    ),
                ),
                (
                    "small_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_preferences",
                        to="auctions.categorysmall",
                        verbose_name="소분류",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 설정",
                "verbose_name_plural": "알림 설정 목록",
                "db_table": "alert_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "이메일"), ("telegram", "텔레그램")],
                        max_length=20,
                        verbose_name="채널",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "발송 대기"),
                            ("success", "발송 성공"),
                            ("failed", "발송 실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "message_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="제목"
                    ),
                ),
                (
                    "message_body",
                    models.TextField(blank=True, null=True, verbose_name="본문"),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="에러 메시지",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제 발송 시각"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="alerts.alertpreference",
                        verbose_name="알림 설정",
                    ),
                ),
                (
                    "auction_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="auctions.auctionitem",
                        verbose_name="매물",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 발송 로그",
                "verbose_name_plural": "알림 발송 로그 목록",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
