# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="alerts.alertpreference",
                verbose_name="알림 설정",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="auction_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="auctions.auctionitem",
                verbose_name="매물",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
    ]
