# Generated by Django 5.2.8 on 2025-12-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryLarge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "대분류",
                "verbose_name_plural": "대분류 목록",
                "db_table": "categories_large",
            },
        ),
        migrations.CreateModel(
            name="CategoryMiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                (
                    "large",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="middles",
                        to="auctions.categorylarge",
                    ),
                ),
            ],
            options={
                "verbose_name": "중분류",
                "verbose_name_plural": "중분류 목록",
                "db_table": "categories_middle",
                "unique_together": {("large", "code")},
            },
        ),
        migrations.CreateModel(
            name="CategorySmall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                (
                    "middle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smalls",
                        to="auctions.categorymiddle",
                    ),
                ),
            ],
            options={
                "verbose_name": "소분류",
                "verbose_name_plural": "소분류 목록",
                "db_table": "categories_small",
                "unique_together": {("middle", "code")},
            },
        ),
        migrations.CreateModel(
            name="AuctionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("court", "법원경매"), ("onbid", "온비드")],
                        max_length=20,
                        verbose_name="데이터 출처",
                    ),
                ),
                (
                    "raw_source",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="원본 출처 코드/텍스트",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("location", models.CharField(max_length=255, verbose_name="소재지")),
                ("area", models.FloatField(blank=True, null=True, verbose_name="면적")),
                ("min_bid_price", models.BigIntegerField(verbose_name="최저입찰가")),
                (
                    "deposit_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="입찰보증금"
                    ),
                ),
                (
                    "appraisal_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="감정가"
                    ),
                ),
                (
                    "auction_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="입찰/매각 예정일"
                    ),
                ),
                (
                    "bid_method",
                    models.CharField(
                        choices=[
                            ("date", "기일입찰"),
                            ("period", "기간입찰"),
                            ("etc", "기타"),
                            ("unknown", "알 수 없음"),
                        ],
                        default="unknown",
                        max_length=30,
                        verbose_name="입찰 방식",
                    ),
                ),
                (
                    "raw_bid_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="원본 입찰 방식",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "입찰 예정"),
                            ("active", "진행 중"),
                            ("sold", "매각/낙찰"),
                            ("failed", "유찰/종료"),
                            ("unknown", "알 수 없음"),
                        ],
                        default="planned",
                        max_length=50,
                        verbose_name="상태",
                    ),
                ),
                (
                    "raw_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="원본 상태 문자열",
                    ),
                ),
                (
                    "num_failures",
                    models.IntegerField(default=0, verbose_name="유찰 횟수"),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="외부 매물 ID"
                    ),
                ),
                (
                    "detail_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="상세 페이지 URL",
                    ),
                ),
                (
                    "large",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorylarge",
                    ),
                ),
                (
                    "middle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorymiddle",
                    ),
                ),
                (
                    "small",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorysmall",
                    ),
                ),
            ],
            options={
                "verbose_name": "매물",
                "verbose_name_plural": "매물 목록",
                "db_table": "auction_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
