# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryLarge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "대분류",
                "verbose_name_plural": "대분류 목록",
                "db_table": "categories_large",
            },
        ),
        migrations.CreateModel(
            name="CategoryMiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                (
                    "large",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="middles",
                        to="auctions.categorylarge",
                    ),
                ),
            ],
            options={
                "verbose_name": "중분류",
                "verbose_name_plural": "중분류 목록",
                "db_table": "categories_middle",
                "unique_together": {("large", "code")},
            },
        ),
        migrations.CreateModel(
            name="CategorySmall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                (
                    "middle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smalls",
                        to="auctions.categorymiddle",
                    ),
                ),
            ],
            options={
                "verbose_name": "소분류",
                "verbose_name_plural": "소분류 목록",
                "db_table": "categories_small",
                "unique_together": {("middle", "code")},
            },
        ),
        migrations.CreateModel(
            name="AuctionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("area", models.FloatField(blank=True, null=True)),
                ("min_bid_price", models.BigIntegerField()),
                ("deposit_price", models.BigIntegerField(blank=True, null=True)),
                ("appraisal_price", models.BigIntegerField(blank=True, null=True)),
                ("auction_date", models.DateField(blank=True, null=True)),
                (
                    "bid_method",
                    models.CharField(
                        blank=True,
                        help_text="입찰방법(예: 기일입찰, 기간입찰 등)",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("num_failures", models.IntegerField(default=0)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("detail_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "large",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorylarge",
                    ),
                ),
                (
                    "middle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorymiddle",
                    ),
                ),
                (
                    "small",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="auctions.categorysmall",
                    ),
                ),
            ],
            options={
                "verbose_name": "매물",
                "verbose_name_plural": "매물 목록",
                "db_table": "auction_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
