# Generated by Django 5.2.8 on 2025-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="raw_bid_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="raw_source",
            field=models.CharField(
                blank=True, help_text="원본 사이트명 그대로", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="raw_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="bid_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "기일입찰"),
                    ("period", "기간입찰"),
                    ("unknown", "알 수 없음"),
                ],
                default="unknown",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="source",
            field=models.CharField(
                choices=[
                    ("court", "법원경매"),
                    ("onbid", "온비드공매"),
                    ("other", "기타"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "진행중"),
                    ("end", "종료"),
                    ("fail", "유찰"),
                    ("unknown", "알 수 없음"),
                ],
                default="unknown",
                max_length=50,
                null=True,
            ),
        ),
    ]
