# Generated by Django 5.2.8 on 2025-12-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="ai_analysis",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI 분석 코멘트"
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="ai_predicted_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="AI 예상 낙찰가"
            ),
        ),
    ]
