# Generated by Django 5.2.8 on 2025-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionitem_raw_bid_method_auctionitem_raw_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="appraisal_price",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="감정가"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="area",
            field=models.FloatField(blank=True, null=True, verbose_name="면적"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="auction_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="입찰/매각 예정일"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="bid_method",
            field=models.CharField(
                choices=[
                    ("date", "기일입찰"),
                    ("period", "기간입찰"),
                    ("etc", "기타"),
                    ("unknown", "알 수 없음"),
                ],
                default="unknown",
                max_length=30,
                verbose_name="입찰 방식",
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="deposit_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="입찰보증금"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="detail_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="상세 페이지 URL"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="external_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="외부 매물 ID"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="location",
            field=models.CharField(max_length=255, verbose_name="소재지"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="min_bid_price",
            field=models.BigIntegerField(verbose_name="최저입찰가"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="num_failures",
            field=models.IntegerField(default=0, verbose_name="유찰 횟수"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="raw_bid_method",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="원본 입찰 방식"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="raw_source",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="원본 출처 코드/텍스트",
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="raw_status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="원본 상태 문자열"
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="source",
            field=models.CharField(
                choices=[("court", "법원경매"), ("onbid", "온비드")],
                max_length=20,
                verbose_name="데이터 출처",
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "입찰 예정"),
                    ("active", "진행 중"),
                    ("sold", "매각/낙찰"),
                    ("failed", "유찰/종료"),
                    ("unknown", "알 수 없음"),
                ],
                default="planned",
                max_length=50,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="title",
            field=models.CharField(max_length=255, verbose_name="제목"),
        ),
    ]
