# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("court", "법원경매"), ("onbid", "온비드")],
                        max_length=20,
                        verbose_name="데이터 출처",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("running", "진행중"),
                            ("success", "성공"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="작업 상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="작업 시작 시각"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="작업 종료 시각"
                    ),
                ),
                (
                    "total_fetched",
                    models.IntegerField(default=0, verbose_name="총 건수"),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, verbose_name="신규 건수"),
                ),
                (
                    "updated_count",
                    models.IntegerField(default=0, verbose_name="업데이트 건수"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="실패 건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="에러 메시지"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="비고"
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 작업",
                "verbose_name_plural": "크롤링 작업 목록",
                "db_table": "crawl_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlItemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="외부 매물 ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("created", "신규 생성"),
                            ("updated", "업데이트"),
                            ("skipped", "변경 없음"),
                            ("failed", "실패"),
                        ],
                        max_length=20,
                        verbose_name="결과",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="메모/에러 내용"
                    ),
                ),
                (
                    "auction_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawl_logs",
                        to="auctions.auctionitem",
                        verbose_name="매물",
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 아이템 로그",
                "verbose_name_plural": "크롤링 아이템 로그 목록",
                "db_table": "crawl_item_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
