# Generated by Django 5.2.8 on 2025-12-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawljob",
            name="source",
            field=models.CharField(
                choices=[("court", "법원경매")],
                max_length=20,
                verbose_name="데이터 출처",
            ),
        ),
    ]
