# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crawljob",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crawl_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="실행 유저",
            ),
        ),
        migrations.AddField(
            model_name="crawlitemlog",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_logs",
                to="operations.crawljob",
                verbose_name="크롤링 작업",
            ),
        ),
    ]
